/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutMe: typeof import('./src/components/landing/AboutMe.vue')['default']
    Button: typeof import('primevue/button')['default']
    Connect: typeof import('./src/components/landing/Connect.vue')['default']
    DecryptedText: typeof import('./src/components/DecryptedText.vue')['default']
    Divider: typeof import('primevue/divider')['default']
    Exeperiencies: typeof import('./src/components/landing/Exeperiencies.vue')['default']
    FirstProject: typeof import('./src/components/landing/FirstProject.vue')['default']
    FirstSection: typeof import('./src/components/landing/FirstSection.vue')['default']
    FloatingConfigurator: typeof import('./src/components/FloatingConfigurator.vue')['default']
    GlassSurface: typeof import('./src/components/GlassSurface.vue')['default']
    More: typeof import('./src/components/landing/More.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollStack: typeof import('./src/components/ScrollStack.vue')['default']
    SecondProject: typeof import('./src/components/landing/SecondProject.vue')['default']
    ShinyText: typeof import('./src/components/ShinyText.vue')['default']
    Skills: typeof import('./src/components/landing/Skills.vue')['default']
    TextPressure: typeof import('./src/components/TextPressure.vue')['default']
    'TextType ': typeof import('./src/components/TextType .vue')['default']
    ThirdPtoject: typeof import('./src/components/landing/ThirdPtoject.vue')['default']
    TopbarWidget: typeof import('./src/components/landing/TopbarWidget.vue')['default']
    VariableProximity: typeof import('./src/components/VariableProximity.vue')['default']
  }
  export interface ComponentCustomProperties {
    AnimateOnScroll: typeof import('primevue/animateonscroll')['default']
  }
}
